/* Generated by AN DISI Unibo */ 
package it.unibo.waste_truck

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waste_truck ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE_TRUCK | INIT")
					}
					 transition( edgeName="goto",targetState="indoor_request", cond=doswitch() )
				}	 
				state("indoor_request") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE_TRUCK | richiesta di prelievo carico")
						request("load_req", "load_req(vetro,10)" ,"waste_service" )  
					}
					 transition(edgeName="t00",targetState="accepted",cond=whenReply("loadaccept"))
					transition(edgeName="t01",targetState="rejected",cond=whenReply("loadrejected"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("Request accepted")
					}
				}	 
				state("rejected") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("Request rejected")
					}
				}	 
			}
		}
}
