/* Generated by AN DISI Unibo */ 
package it.unibo.waste_service

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waste_service ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var MAXPB = 10
				var MAXGB = 10
				var CurrentPlasticWeight=0
				var CurrentGlassWeight=0
				var Trolley_occupato=false	
				var Carico_accettato = false
				var Tipo_carico = ""
				var Peso_carico = 0
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | START")
					}
					 transition( edgeName="goto",targetState="attesa_load_req", cond=doswitch() )
				}	 
				state("attesa_load_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTESA LOAD REQUEST(CAMION)")
					}
					 transition(edgeName="t03",targetState="gestisci_richiesta",cond=whenRequest("load_req"))
				}	 
				state("gestisci_richiesta") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | GESTIONE RICHIESTA")
						if( checkMsgContent( Term.createTerm("load_req(TYPE,WEIGHT)"), Term.createTerm("load_req(TYPE,WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Tipo_carico = payloadArg(0)
												Peso_carico = payloadArg(1).toInt()
												if (Tipo_carico  == "plastica") {
													Carico_accettato = (CurrentPlasticWeight + Peso_carico <= MAXPB)
												} else if (Tipo_carico  == "vetro") {
													Carico_accettato = ( CurrentGlassWeight + Peso_carico <= MAXGB)
												} else {
													Carico_accettato = false
													println("WASTE SERVICE | Tipo sbagliato")
												}
								if(  ! Carico_accettato  
								 ){answer("load_req", "loadrejected", "loadrejected(Type,Weight)"   )  
								}
						}
					}
					 transition( edgeName="goto",targetState="attiva_deposito", cond=doswitchGuarded({ Carico_accettato  
					}) )
					transition( edgeName="goto",targetState="attesa_load_req", cond=doswitchGuarded({! ( Carico_accettato  
					) }) )
				}	 
				state("attiva_deposito") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTIVA DEPOSITO")
						request("start_trasf", "start_trasf($Tipo_carico)" ,"trolley" )  
					}
					 transition(edgeName="t14",targetState="libera_indoor",cond=whenReply("load_pickup"))
				}	 
				state("libera_indoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | LIBERA INDOOR")
						if( checkMsgContent( Term.createTerm("load_pickup(ok)"), Term.createTerm("load_pickup(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("load_req", "loadaccept", "yes($Tipo_carico,$Peso_carico)"   )  
						}
						
									if (Tipo_carico  == "plastica") {
											CurrentPlasticWeight = CurrentPlasticWeight + Peso_carico
									} else if (Tipo_carico  == "vetro") {
											CurrentGlassWeight = CurrentGlassWeight + Peso_carico
									}
					}
					 transition( edgeName="goto",targetState="attesa_load_req", cond=doswitch() )
				}	 
			}
		}
}
