/* Generated by AN DISI Unibo */ 
package it.unibo.wastetruckmock3

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wastetruckmock3 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 3 | START")
						delay(4000) 
					}
					 transition( edgeName="goto",targetState="camion5_req", cond=doswitch() )
				}	 
				state("camion5_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(250) 
						println("WASTE TRUCK 3| CAMION 5 REQ (PLASTIC, 8)")
						request("load_req", "load_req(P,8)" ,"waste_service" )  
					}
					 transition(edgeName="t018",targetState="camion5_accepted",cond=whenReply("loadrejected"))
					transition(edgeName="t019",targetState="not_as_planned",cond=whenReply("loadaccepted"))
				}	 
				state("camion5_accepted") { //this:State
					action { //it:State
						println("WASTE TRUCK 3 | CAMION 5 rifiutato")
					}
					 transition( edgeName="goto",targetState="camion5_terminazione", cond=doswitch() )
				}	 
				state("camion5_terminazione") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 3| CAMION 5 TERMINA")
					}
					 transition( edgeName="goto",targetState="fine", cond=doswitch() )
				}	 
				state("not_as_planned") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 3| ERRORE!!!!!")
					}
				}	 
				state("fine") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 3| FINE!")
					}
				}	 
			}
		}
}
