/* Generated by AN DISI Unibo */ 
package it.unibo.wastetruckmock2

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wastetruckmock2 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						delay(250) 
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2 | START")
					}
					 transition( edgeName="goto",targetState="camion_req", cond=doswitch() )
				}	 
				state("camion_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						 
									var Peso_carico    = kotlin.random.Random.nextInt(0,10)
									var TipoInt = kotlin.random.Random.nextInt(0,1)
									var Tipo_carico    = ""
									
									if(TipoInt == 0) 
										Tipo_carico = "vetro"
									else
										Tipo_carico = "plastica"
						println("WASTE TRUCK 2 | CAMION REQ ($Tipo_carico, $Peso_carico)")
						request("load_req", "load_req($Tipo_carico,$Peso_carico)" ,"waste_service" )  
					}
					 transition(edgeName="t07",targetState="camion_accepted",cond=whenReply("loadaccept"))
					transition(edgeName="t08",targetState="camion_rejected",cond=whenReply("loadrejected"))
				}	 
				state("camion_rejected") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2 | CAMION 2 RIFIUTATO")
					}
					 transition( edgeName="goto",targetState="fine", cond=doswitch() )
				}	 
				state("camion_accepted") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2 | CAMION 2 ACCETTATO  CIAOOO")
					}
					 transition( edgeName="goto",targetState="fine", cond=doswitch() )
				}	 
				state("fine") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2 | FINE!")
					}
				}	 
			}
		}
}
