/* Generated by AN DISI Unibo */ 
package it.unibo.wasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				WasteServiceConfigurator.setTheConfiguration("./resources/WasteServiceConfig.json")
				var MAXPB = WasteServiceConfigurator.MAXPB
				var MAXGB = WasteServiceConfigurator.MAXGB
				var CurrentPlasticWeight=WasteServiceConfigurator.CurPWeight
				var CurrentGlassWeight=WasteServiceConfigurator.CurGWeight
				var Trolley_home=true	
				var Carico_accettato = false
				var Tipo_carico = ""
				var Peso_carico = 0
				var PercorsoCurr = ""
				var Resumed = false
				val XIndoor = WasteServiceConfigurator.XIndoor
				val YIndoor = WasteServiceConfigurator.YIndoor
				val XVetro =  WasteServiceConfigurator.XGBox
				val YVetro =  WasteServiceConfigurator.YGBox
				val XPlastica = WasteServiceConfigurator.XPBox		
				val YPlastica = WasteServiceConfigurator.YPBox
				val XHome = WasteServiceConfigurator.XHome
				val YHome = WasteServiceConfigurator.YHome
				
				var LastState = "home"
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						unibo.kotlin.planner22Util.loadRoomMap( "mapRoomEmpty"  )
						unibo.kotlin.planner22Util.initAI(  )
						unibo.kotlin.planner22Util.showCurrentRobotState(  )
						println("WASTE SERVICE | START")
						forward("cmd", "cmd(off)" ,"led" ) 
					}
					 transition( edgeName="goto",targetState="attesa_load_req", cond=doswitch() )
				}	 
				state("attesa_load_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTESA LOAD REQUEST(CAMION)")
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								delay(200) 
						}
					}
					 transition(edgeName="t032",targetState="gestisci_richiesta",cond=whenRequest("load_req"))
					transition(edgeName="t033",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("gestisci_richiesta") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | GESTIONE RICHIESTA")
						if( checkMsgContent( Term.createTerm("load_req(TYPE,WEIGHT)"), Term.createTerm("load_req(TYPE,WEIGHT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Tipo_carico = payloadArg(0)
												Peso_carico = payloadArg(1).toInt()
												if (Tipo_carico  == "plastica") {
													Carico_accettato = (CurrentPlasticWeight + Peso_carico <= MAXPB)
												} else if (Tipo_carico  == "vetro") {
													Carico_accettato = ( CurrentGlassWeight + Peso_carico <= MAXGB)
												} else {
													Carico_accettato = false
													println("WASTE SERVICE | Tipo sbagliato")
												}
								if(  ! Carico_accettato  
								 ){answer("load_req", "loadrejected", "loadrejected($Tipo_carico,$Peso_carico)"   )  
								}
						}
					}
					 transition( edgeName="goto",targetState="attiva_indoor", cond=doswitchGuarded({ Carico_accettato  
					}) )
					transition( edgeName="goto",targetState="go_home", cond=doswitchGuarded({! ( Carico_accettato  
					) }) )
				}	 
				state("attiva_indoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTIVA INDOOR $Resumed")
						 
									Trolley_home = false
									LastState = "go_indoor"
									
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								delay(200) 
						}
						forward("cmd", "cmd(blink)" ,"led" ) 
						if(  Resumed==false  
						 ){unibo.kotlin.planner22Util.setGoal( XIndoor, YIndoor  )
						 PercorsoCurr = unibo.kotlin.planner22Util.doPlan().toString()  //List<aima.core.agent.Action>  [w, w, l, w] 
										.replace(" ","")
										.replace(",","")
										.replace("[","")
										.replace("]","")
						request("go_indoor", "go_indoor($PercorsoCurr)" ,"trolley" )  
						}
						else
						 { Resumed = false  
						 }
						println("ATTIVA INDOOR ALGISE")
					}
					 transition(edgeName="t134",targetState="attiva_pickup",cond=whenReply("indoor_done"))
					transition(edgeName="t135",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("attiva_pickup") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTIVA PICKUP")
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								forward("cmd", "cmd(blink)" ,"led" ) 
								delay(200) 
						}
						if( checkMsgContent( Term.createTerm("indoor_done(ok)"), Term.createTerm("indoor_done(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								request("pickup", "pickup(arg)" ,"trolley" )  
						}
						 LastState = "pickup"
									Resumed = false 
					}
					 transition(edgeName="t136",targetState="attiva_trasferimento",cond=whenReply("pickup_done"))
					transition(edgeName="t137",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("attiva_trasferimento") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTIVA TRASFERIMENTO (IL CAMION LIBERA INDOOR)")
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								forward("cmd", "cmd(blink)" ,"led" ) 
								delay(200) 
						}
						if( checkMsgContent( Term.createTerm("pickup_done(ok)"), Term.createTerm("pickup_done(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("load_req", "loadaccept", "loadaccept($Tipo_carico,$Peso_carico)"   )  
								unibo.kotlin.planner22Util.updateMapWithPath( PercorsoCurr  )
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
								
												if (Tipo_carico  == "plastica") {
														
								unibo.kotlin.planner22Util.setGoal( XPlastica, YPlastica  )
										
												} else if (Tipo_carico  == "vetro") {
														
								unibo.kotlin.planner22Util.setGoal( XVetro, YVetro  )
								
												}
											
											PercorsoCurr = unibo.kotlin.planner22Util.doPlan().toString() 
												.replace(" ","")
												.replace(",","")
												.replace("[","")
												.replace("]","")
								request("trasf", "trasf($PercorsoCurr)" ,"trolley" )  
						}
						 LastState = "trasferimento" 
										Resumed = false 
					}
					 transition(edgeName="t238",targetState="attiva_deposito",cond=whenReply("trasf_done"))
					transition(edgeName="t239",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("attiva_deposito") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | ATTIVA DEPOSITO")
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								forward("cmd", "cmd(blink)" ,"led" ) 
								delay(200) 
						}
						if( checkMsgContent( Term.createTerm("trasf_done(ok)"), Term.createTerm("trasf_done(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								unibo.kotlin.planner22Util.updateMapWithPath( PercorsoCurr  )
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
								request("deposit", "deposit(arg)" ,"trolley" )  
						}
						 LastState = "deposito" 
									Resumed = false  
					}
					 transition(edgeName="t340",targetState="controlla_req",cond=whenReply("deposit_done"))
					transition(edgeName="t341",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("controlla_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | CONTROLLA NUOVE RICHIESTE")
						
										if (Tipo_carico  == "plastica") {
												CurrentPlasticWeight = CurrentPlasticWeight + Peso_carico
						updateResourceRep( "PBOX:$CurrentPlasticWeight"  
						)
								
										} else if (Tipo_carico  == "vetro") {
												CurrentGlassWeight = CurrentGlassWeight + Peso_carico
						updateResourceRep( "GBOX:$CurrentGlassWeight"  
						)
						
										}
						Resumed = false 
						stateTimer = TimerActor("timer_controlla_req", 
							scope, context!!, "local_tout_wasteservice_controlla_req", 100.toLong() )
					}
					 transition(edgeName="t442",targetState="go_home",cond=whenTimeout("local_tout_wasteservice_controlla_req"))   
					transition(edgeName="t443",targetState="gestisci_richiesta",cond=whenRequest("load_req"))
					transition(edgeName="t444",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("go_home") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | GO HOME")
						if( checkMsgContent( Term.createTerm("resume(STATE)"), Term.createTerm("resume(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("resume", "resume($LastState)" ,"trolley" ) 
								forward("cmd", "cmd(blink)" ,"led" ) 
								delay(200) 
						}
						if(  ! Resumed  
						 ){unibo.kotlin.planner22Util.setGoal( XHome, YHome  )
						
									PercorsoCurr = unibo.kotlin.planner22Util.doPlan().toString() 
										.replace(" ","")
										.replace(",","")
										.replace("[","")
										.replace("]","")
						request("ritorno_home", "ritorno_home($PercorsoCurr)" ,"trolley" )  
						 
										Trolley_home = true
										LastState = "ritorno_home"
						}
						else
						 { Resumed = false 
						 }
					}
					 transition(edgeName="t545",targetState="ritorno_done",cond=whenReply("home_done"))
					transition(edgeName="t546",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("ritorno_done") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("home_done(ok)"), Term.createTerm("home_done(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("cmd", "cmd(off)" ,"led" ) 
								unibo.kotlin.planner22Util.updateMapWithPath( PercorsoCurr  )
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
						}
						 LastState = "home" 
									Resumed = false 
					}
					 transition( edgeName="goto",targetState="attesa_load_req", cond=doswitch() )
				}	 
				state("stopped") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE SERVICE | STOPPED")
						forward("stop", "stop(STOP)" ,"trolley" ) 
						forward("cmd", "cmd(on)" ,"led" ) 
						 Resumed = true  
					}
					 transition(edgeName="t647",targetState="attesa_load_req",cond=whenDispatchGuarded("resume",{ LastState == "home"  
					}))
					transition(edgeName="t648",targetState="attiva_indoor",cond=whenDispatchGuarded("resume",{ LastState == "go_indoor"  
					}))
					transition(edgeName="t649",targetState="attiva_pickup",cond=whenDispatchGuarded("resume",{ LastState == "pickup"  
					}))
					transition(edgeName="t650",targetState="attiva_trasferimento",cond=whenDispatchGuarded("resume",{ LastState == "trasferimento"  
					}))
					transition(edgeName="t651",targetState="attiva_deposito",cond=whenDispatchGuarded("resume",{ LastState == "deposito"  
					}))
					transition(edgeName="t652",targetState="go_home",cond=whenDispatchGuarded("resume",{ LastState == "ritorno_home"  
					}))
				}	 
			}
		}
}
