/* Generated by AN DISI Unibo */ 
package it.unibo.wastetruckmock2

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wastetruckmock2 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2 | START")
						delay(4000) 
					}
					 transition( edgeName="goto",targetState="camion4_req", cond=doswitch() )
				}	 
				state("camion4_req") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(250) 
						println("WASTE TRUCK 2| CAMION 4 REQ (PLASTIC, 3)")
						request("load_req", "load_req(P,3)" ,"waste_service" )  
					}
					 transition(edgeName="t015",targetState="camion4_accepted",cond=whenReply("loadaccepted"))
					transition(edgeName="t016",targetState="not_as_planned",cond=whenReply("loadrejected"))
				}	 
				state("camion4_accepted") { //this:State
					action { //it:State
						println("WASTE TRUCK 2 | CAMION 4 ACCETTATO")
					}
					 transition(edgeName="t117",targetState="camion4_terminazione",cond=whenEvent("load_pickup"))
				}	 
				state("camion4_terminazione") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2| CAMION 4 TERMINA")
					}
					 transition( edgeName="goto",targetState="fine", cond=doswitch() )
				}	 
				state("not_as_planned") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2| ERRORE!!!!!")
					}
				}	 
				state("fine") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTE TRUCK 2| FINE!")
					}
				}	 
			}
		}
}
